steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/mes-server', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/mes-server']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'mes-server', '--image', 'gcr.io/$PROJECT_ID/mes-server', '--platform', 'managed', '--region', 'us-central1', '--allow-unauthenticated']
